name = "ghostclip-worker"
main = "src/index.ts"
compatibility_date = "2025-03-01"
workers_dev = true

# 自定义域名
routes = [
  { pattern = "ghostclip.no-bug.dev", custom_domain = true }
]

[[kv_namespaces]]
binding = "KV"
id = "531a204d1a6345efac8f8ff74aff7a7b"
